<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>BOTW.DedicatedServer</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="BOTW.DedicatedServer.AppdataFiles.ArmorMapping.txt" />
    <None Remove="BOTW.DedicatedServer.AppdataFiles.QuestFlagsNames.txt" />
    <EmbeddedResource Include="BOTW.DedicatedServer.AppdataFiles.ArmorMapping.txt" LogicalName="BOTW.DedicatedServer.AppdataFiles.ArmorMapping.txt" />
    <EmbeddedResource Include="BOTW.DedicatedServer.AppdataFiles.QuestFlagsNames.txt" LogicalName="BOTW.DedicatedServer.AppdataFiles.QuestFlagsNames.txt" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Collections">
      <HintPath>../../../../../../../../opt/ilspy/System.Collections.dll</HintPath>
    </Reference>
    <Reference Include="BOTWM.Server">
      <HintPath>../BOTWM.Server.dll</HintPath>
    </Reference>
    <Reference Include="System.Console">
      <HintPath>../../../../../../../../opt/ilspy/System.Console.dll</HintPath>
    </Reference>
    <Reference Include="System.Linq">
      <HintPath>../../../../../../../../opt/ilspy/System.Linq.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>../../../../../../../../opt/ilspy/Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading">
      <HintPath>../../../../../../../../opt/ilspy/System.Threading.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>